# Generated by Django 5.0.6 on 2024-06-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="seasonal_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.seasonalevents",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.producttype",
            ),
        ),
    ]
